### ISSUE TITLE
error

### ISSUE THREAD

**Issue by smoochiee** [NightRyderrr/EvilPortal-ESP32#1]
c:\Users\Dell\Documents\Arduino\libraries\ESPAsyncWebServer\src\AsyncWebSocket.cpp: In member function 'IPAddress AsyncWebSocketClient::remoteIP()':
c:\Users\Dell\Documents\Arduino\libraries\ESPAsyncWebServer\src\AsyncWebSocket.cpp:832:28: error: call of overloaded 'IPAddress(unsigned int)' is ambiguous
         return IPAddress(0U);
                            ^
In file included from C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/Arduino.h:180,
                 from c:\Users\Dell\Documents\Arduino\libraries\ESPAsyncWebServer\src\AsyncWebSocket.cpp:21:
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/IPAddress.h:51:5: note: candidate: 'IPAddress::IPAddress(const uint8_t*)'
     IPAddress(const uint8_t *address);
     ^~~~~~~~~
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/IPAddress.h:50:5: note: candidate: 'IPAddress::IPAddress(uint32_t)'
     IPAddress(uint32_t address);
     ^~~~~~~~~
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\cores\esp32/IPAddress.h:29:7: note: candidate: 'constexpr IPAddress::IPAddress(const IPAddress&)'
 class IPAddress: public Printable
       ^~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by NightRyderrr** [comment]
looks like an issue with your downloaded libraries

**Comment by smoochiee** [comment]
> IPAddress.h:29:7: note: candidate: 'constexpr IPAddress::IPAddress(const IPAddress&)'

can you give me version of your library
or can you upload it here

**Comment by smoochiee** [comment]
> looks like an issue with your downloaded libraries
can you give me version of your library
or can you upload it here

**Comment by smoochiee** [comment]
> looks like an issue with your downloaded libraries

can you give me version of your library
or can you upload it here

**Comment by smoochiee** [comment]
> looks like an issue with your downloaded libraries

its board problem.....not compatible with xiao esp32c3...ty
